# render.yaml
services:
  - type: web
    name: ethio-match
    env: node
    buildCommand: npm install
    startCommand: node server.js
    nodeVersion: "20.x"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CSRF_SECRET
        sync: false
