git add render.yaml
git commit -m "Add render.yaml"
git push
services:
  - type: web
    name: ethio-match
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
